language: python
python:
    # We don't actually use the Travis Python, but this keeps it organized.
    - "3.5"
install:
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda

    # Useful for debugging any issues with conda
    - conda info -a

    # Install Python and required packages.
    - conda env create -f environment.yml
    - source activate sgbs-training


script:
    # Execute build command
    - mkdocs build


# Using Travis' GitHub pages deployment: https://docs.travis-ci.com/user/deployment/pages/
# Docs are here: https://docs.travis-ci.com/user/deployment/pages/#further-configuration
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
        branch: master
    local-dir: site
    target-branch: gh-pages
    verbose: true
