name: sgbs-training
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pygments
  - pre-commit
  - jupyter
  - ipykernel
  - pip
  - panel
  - jupyter_bokeh
  - pip:
      - mkdocs-minify-plugin
      - pymdown-extensions
      - mkdocs
      - mkdocs-material
      - google-auth-httplib2
      - google-api-python-client
      - PyDrive2
      - pyprojroot
      - python-dotenv
