# This GitHub workflow runs only on push to master.
# By this point, we are assuming that all checks on the PR,
# which are checked by the Azure Pipeline, have passed.
# The full pipeline is also leveraged here,
# as we don't want a broken website to be deployed anyways.

name: Master branch deploy

on:
  push:
    branches:
      - master

jobs:
  build-website:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      # See: https://github.com/marketplace/actions/setup-conda
      - uses: s-weigand/setup-conda@v1
        with:
          conda-channels: "conda-forge"

      - name: Build environment
        run: |
          conda env create -f environment.yml

      - name: Build website
        run: |
          source activate sgbs-training
          mkdocs build

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-personal-access-token-personal_token
          personal_token: ${{ secrets.GHPAGES_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: true
          enable_jekyll: false
          disable_nojekyll: false
