name: Deploy to Dokku Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@v1.6.0
        with:
          branch: 'main'
          git_remote_url: ${{ secrets.DOKKU_GIT_REMOTE_URL}}
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          trace: 1
